import { useState, useRef, useEffect } from 'react';
import { MessageCircle, X, Send, ArrowUpRight } from 'lucide-react';
import { submitLeadToOps } from '../lib/leads';
import {
  fetchOwnerProfile,
  signInWithGoogle,
  sendMagicLink,
  signOut,
  type OwnerProfile,
} from '../lib/ownerAuth';
import { getSupabase } from '../lib/supabaseClient';

/**
 * Arthur — the Stellar site concierge.
 *
 * Two brains, one widget:
 *  1. If the /api/chat serverless function is configured (ANTHROPIC_API_KEY
 *     set in Vercel), replies are generated by Claude with a strict,
 *     facts-only system prompt.
 *  2. If the API is absent or errors, Arthur falls back to a built-in
 *     knowledge base matched by keywords — so the widget always works and
 *     never invents information.
 * Leads are captured in-chat and delivered via Web3Forms (same pipeline as
 * the site's other forms).
 */

interface Msg {
  role: 'user' | 'assistant';
  content: string;
}

const KB: { keywords: string[]; answer: string }[] = [
  {
    keywords: ['pay', 'payment', 'bill', 'assessment', 'dues', 'autopay', 'echeck', 'credit card'],
    answer:
      'Two ways to pay assessments: (1) Free — set up Bill Pay with your own bank: payee "Your Association Name", mailed to 5107 N. Western Avenue, Suite 1S, Chicago, IL 60625, memo = your association\'s 4-number address and unit number. (2) Online — the AppFolio portal at stellarpropertygrp.appfolio.com/connect/ takes eCheck or card and supports autopay. Full details: stellarpropertygroup.com/resources#bill-pay',
  },
  {
    keywords: ['portal', 'login', 'log in', 'appfolio', 'account', 'password', 'invitation', 'access'],
    answer:
      'The owner & resident portal is at stellarpropertygrp.appfolio.com/connect/ — payments, autopay, maintenance requests, and documents. New residents receive an email invitation during onboarding; if you need one, call 773.728.0652 or email mirsad@stellarpropertygroup.com and we\'ll send it within one business day.',
  },
  {
    keywords: ['emergency', 'flood', 'flooding', 'fire', 'elevator', 'boiler', 'leak', 'urgent', 'burst'],
    answer:
      'For life-threatening emergencies call 911 first. For building emergencies — flooding, fire damage, elevator entrapment, boiler failure — call our 24/7 line at 773.728.0652. A live member of our Chicago team answers around the clock and dispatches vetted crews immediately.',
  },
  {
    keywords: ['violation', 'complaint', 'noise', 'report', 'neighbor', 'rules', 'airbnb', 'sublet'],
    answer:
      'You can file a formal violation report online at stellarpropertygroup.com/resources?form=violation — it goes directly to our management team and becomes part of your association\'s records, handled with proper due process under Illinois law.',
  },
  {
    keywords: ['maintenance', 'repair', 'request', 'broken', 'fix', 'work order'],
    answer:
      'Submit maintenance requests through the AppFolio portal (stellarpropertygrp.appfolio.com/connect/) under "Maintenance Requests" — you can attach photos and track progress. For after-hours emergencies, call 773.728.0652 any time.',
  },
  {
    keywords: ['price', 'pricing', 'cost', 'fee', 'quote', 'how much', 'charge'],
    answer:
      'We quote a customized flat monthly fee based on your building\'s size, amenities, and service scope — never a percentage of your budget. For exact pricing, request a free proposal at stellarpropertygroup.com/contact or call 773.728.0652.',
  },
  {
    keywords: ['switch', 'change', 'transition', 'leave', 'current manager', 'new management', 'proposal', 'hire'],
    answer:
      'Switching to Stellar is a managed 30–60 day transition: we retrieve records from your outgoing firm, migrate banking and vendor relationships, notify owners, and open your portals — your board only signs. Start with a free proposal at stellarpropertygroup.com/contact.',
  },
  {
    keywords: ['area', 'neighborhood', 'serve', 'location', 'where', 'evanston', 'wilmette', 'winnetka', 'gold coast', 'lincoln park', 'north shore', 'suburb'],
    answer:
      'We serve 70+ Chicago neighborhoods — from the Gold Coast and Streeterville to Lincoln Park, Lakeview, and Hyde Park — plus North Shore communities including Evanston, Skokie, Glenview, Wilmette, Winnetka, Highland Park, Northbrook, Glencoe, Kenilworth, Lake Forest, and Deerfield. Browse them all at stellarpropertygroup.com/service-areas',
  },
  {
    keywords: ['board', 'nomination', 'nominate', 'election', 'director', 'serve on'],
    answer:
      'Interested in serving on your association\'s board? Submit a nomination at stellarpropertygroup.com/resources?form=nomination. We also provide new-director orientation covering governing documents, finances, and fiduciary duties.',
  },
  {
    keywords: ['document', 'bylaws', 'declaration', 'meeting', 'minutes', 'budget'],
    answer:
      'Governing documents, budgets, and meeting materials live in the document section of your AppFolio portal (stellarpropertygrp.appfolio.com/connect/). Board meeting schedules vary by community — check the portal or contact your property manager.',
  },
  {
    keywords: ['contact', 'phone', 'email', 'office', 'address', 'call', 'speak', 'human', 'person'],
    answer:
      'Reach us at 773.728.0652 (24/7 for emergencies) or mirsad@stellarpropertygroup.com. Office: 5107 N Western Ave, Suite 1S, Chicago, IL 60625. Or use the contact form at stellarpropertygroup.com/contact.',
  },
  {
    keywords: ['service', 'what do you do', 'manage', 'offer', 'condo', 'hoa', 'townhome', 'rental', 'apartment'],
    answer:
      'We manage condominium associations, HOAs, and townhome communities exclusively — no apartment rentals. Services span daily operations, flat-fee financial management, maintenance with 24/7 response, board support, and violation management. Since 2007: 42 associations, 2,450+ residences, 96% retention. Details: stellarpropertygroup.com/services',
  },
];

function kbAnswer(text: string): string {
  const q = text.toLowerCase();
  let best: { score: number; answer: string } = { score: 0, answer: '' };
  for (const entry of KB) {
    const score = entry.keywords.reduce((s, k) => (q.includes(k) ? s + (k.length > 5 ? 2 : 1) : s), 0);
    if (score > best.score) best = { score, answer: entry.answer };
  }
  if (best.score > 0) return best.answer;
  return 'I can help with payments, the resident portal, maintenance, violations, our service areas, or getting a management proposal for your association. Which of those can I help with? For anything else, call 773.728.0652 or email mirsad@stellarpropertygroup.com.';
}

const GREETING: Msg = {
  role: 'assistant',
  content:
    'Good day — I\'m Arthur, Stellar\'s concierge. I can help with paying assessments, the resident portal, maintenance, violations, our service areas, or a management proposal for your board. How may I help?',
};

const CHIPS = ['How do I pay?', 'Portal help', 'Report a violation', 'Request a proposal'];

// Conversation survives page navigation within the visit (sessionStorage).
const STORAGE_KEY = 'arthur-chat-v1';

function loadStoredMessages(): Msg[] {
  try {
    const raw = sessionStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as Msg[];
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch { /* SSR or storage unavailable */ }
  return [GREETING];
}

// Arthur cites URLs as plain text (often without a protocol) — render them
// as links. Stellar's own pages stay in-tab; everything else opens new.
const LINK_RE = /(https?:\/\/[^\s)]+|(?:stellarpropertygroup\.com|stellarpropertygrp\.appfolio\.com)\/[^\s)]*)/g;

function linkify(text: string) {
  // LINK_RE has one capture group, so split() alternates text/match/text/…
  const parts = text.split(LINK_RE);
  return parts.map((part, i) => {
    if (i % 2 === 0) return part;
    const raw = part.replace(/[.,;:]+$/, '');
    const trailing = part.slice(raw.length);
    const internal = raw.replace(/^https?:\/\/(www\.)?/, '').startsWith('stellarpropertygroup.com');
    const href = internal
      ? raw.slice(raw.indexOf('stellarpropertygroup.com') + 'stellarpropertygroup.com'.length) || '/'
      : raw.startsWith('http') ? raw : `https://${raw}`;
    return (
      <span key={i}>
        <a
          href={href}
          {...(internal ? {} : { target: '_blank', rel: 'noopener noreferrer' })}
          className="text-gold-600 underline decoration-gold-300 underline-offset-2 hover:text-gold-500 break-all"
        >
          {raw}
        </a>
        {trailing}
      </span>
    );
  });
}

export default function ArthurConcierge() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<Msg[]>(loadStoredMessages);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const [leadMode, setLeadMode] = useState(false);
  const [lead, setLead] = useState({ name: '', email: '', building: '' });
  const [leadSent, setLeadSent] = useState(false);
  const [owner, setOwner] = useState<OwnerProfile | null>(null);
  const [authView, setAuthView] = useState<'chat' | 'signin'>('chat');
  const [signinEmail, setSigninEmail] = useState('');
  const [linkSent, setLinkSent] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages, leadMode, open, authView]);

  useEffect(() => {
    try {
      sessionStorage.setItem(STORAGE_KEY, JSON.stringify(messages.slice(-30)));
    } catch { /* storage unavailable */ }
  }, [messages]);

  // Detect an existing (or just-completed magic-link/Google) session and
  // load the owner's profile — reads are RLS-scoped to their own records.
  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      const profile = await fetchOwnerProfile();
      if (!cancelled) setOwner(profile);
    };
    load();
    const { data: sub } = getSupabase().auth.onAuthStateChange((event) => {
      if (event === 'SIGNED_IN') load();
      if (event === 'SIGNED_OUT') setOwner(null);
    });
    return () => {
      cancelled = true;
      sub.subscription.unsubscribe();
    };
  }, []);

  // Personalized greeting once an owner is recognized on a fresh conversation.
  useEffect(() => {
    if (owner && messages.length === 1) {
      const first = owner.name.split(' ')[0];
      const where = [owner.unitNumber && `unit ${owner.unitNumber}`, owner.associationName]
        .filter(Boolean)
        .join(' at ');
      setMessages([
        {
          role: 'assistant',
          content: `Welcome back, ${first}${where ? ` — ${where}` : ''}. I can help with payments, maintenance, documents, or anything about your community. How may I help today?`,
        },
      ]);
      setAuthView('chat');
    }
  }, [owner]); // eslint-disable-line react-hooks/exhaustive-deps

  const ask = async (text: string) => {
    const trimmed = text.trim();
    if (!trimmed || busy) return;
    if (/proposal|quote|hire|interested in management/i.test(trimmed) && !leadSent) {
      setMessages((m) => [...m, { role: 'user', content: trimmed }]);
      setLeadMode(true);
      setInput('');
      return;
    }

    const next: Msg[] = [...messages, { role: 'user', content: trimmed }];
    setMessages(next);
    setInput('');
    setBusy(true);

    try {
      // Signed-in owners: pass the session token so the server can pull
      // their profile and association knowledge under their own RLS scope.
      let token: string | null = null;
      if (owner) {
        try {
          token = (await getSupabase().auth.getSession()).data.session?.access_token ?? null;
        } catch {
          token = null;
        }
      }
      const r = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({
          messages: next.slice(1), // drop greeting
          stream: true,
          ownerContext: owner
            ? { name: owner.name, unit: owner.unitNumber, association: owner.associationName }
            : null,
        }),
      });
      if (!r.ok) throw new Error(String(r.status));

      const contentType = r.headers.get('content-type') || '';
      if (r.body && contentType.includes('text/plain')) {
        // Streamed reply: append the bubble on the first token, then grow it.
        const reader = r.body.getReader();
        const decoder = new TextDecoder();
        let acc = '';
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          acc += decoder.decode(value, { stream: true });
          const content = acc;
          setMessages((m) =>
            m[m.length - 1]?.role === 'assistant' && m.length > next.length
              ? [...m.slice(0, -1), { role: 'assistant', content }]
              : [...m, { role: 'assistant', content }]
          );
        }
        if (!acc.trim()) throw new Error('empty stream');
      } else {
        // Older deployment (or non-stream response): plain JSON reply.
        const data = await r.json();
        const reply: string = data.reply || kbAnswer(trimmed);
        setMessages((m) => [...m, { role: 'assistant', content: reply }]);
      }
    } catch {
      setMessages((m) => {
        const base = m[m.length - 1]?.role === 'assistant' && m.length > next.length ? m.slice(0, -1) : m;
        return [...base, { role: 'assistant', content: kbAnswer(trimmed) }];
      });
    }
    setBusy(false);
  };

  const submitLead = async () => {
    if (!lead.name || !lead.email) return;
    setBusy(true);
    const transcript = messages.map((m) => `${m.role}: ${m.content}`).join('\n').slice(0, 4000);
    try {
      // Delivered two ways: email (Web3Forms) + the stellar-ops database
      // (website_leads), so the ops app sees every website lead.
      const [emailResult] = await Promise.allSettled([
        fetch('https://api.web3forms.com/submit', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            access_key: import.meta.env.VITE_WEB3FORMS_ACCESS_KEY,
            subject: `Website Concierge Lead — ${lead.name}`,
            from_name: 'Arthur (Site Concierge)',
            name: lead.name,
            email: lead.email,
            building: lead.building,
            transcript,
          }),
        }),
        submitLeadToOps({ name: lead.name, email: lead.email, building: lead.building, transcript }),
      ]);
      void emailResult;
      setLeadSent(true);
      setLeadMode(false);
      setMessages((m) => [
        ...m,
        {
          role: 'assistant',
          content: `Thank you, ${lead.name.split(' ')[0]} — your request is with our managing partners and you'll hear from us within one business day. If it's time-sensitive, call 773.728.0652.`,
        },
      ]);
    } catch {
      setMessages((m) => [
        ...m,
        { role: 'assistant', content: 'Something went wrong sending that — please call 773.728.0652 or email mirsad@stellarpropertygroup.com and we\'ll take care of you.' },
      ]);
      setLeadMode(false);
    }
    setBusy(false);
  };

  return (
    <>
      {/* Launcher */}
      <button
        onClick={() => setOpen(!open)}
        aria-label={open ? 'Close concierge chat' : 'Chat with Arthur, our concierge'}
        className="fixed bottom-6 right-6 z-[60] flex items-center gap-3 bg-ink text-paper pl-4 pr-5 py-3.5 shadow-glass hover:bg-navy-700 transition-colors duration-300"
      >
        {open ? <X className="w-5 h-5" strokeWidth={1.5} /> : <MessageCircle className="w-5 h-5 text-gold-300" strokeWidth={1.5} />}
        <span className="text-[11px] font-semibold uppercase tracking-luxe">{open ? 'Close' : 'Ask Arthur'}</span>
      </button>

      {/* Panel */}
      {open && (
        <div className="fixed bottom-24 right-6 z-[60] w-[calc(100vw-3rem)] max-w-md bg-paper border border-slate-200 shadow-glass flex flex-col" style={{ height: 'min(600px, calc(100vh - 8rem))' }}>
          {/* Header */}
          <div className="bg-ink text-paper px-6 py-5">
            <p className="text-[9px] uppercase tracking-luxe text-gold-300 mb-1">Stellar Property Management</p>
            <div className="flex items-center justify-between gap-4">
              <p className="font-display text-xl">Arthur, at your service.</p>
              {owner ? (
                <button
                  onClick={() => { signOut(); setMessages([GREETING]); }}
                  className="text-[9px] uppercase tracking-luxe text-paper/50 hover:text-gold-300 transition-colors whitespace-nowrap"
                >
                  Sign out
                </button>
              ) : (
                <button
                  onClick={() => setAuthView(authView === 'signin' ? 'chat' : 'signin')}
                  className="text-[9px] uppercase tracking-luxe text-gold-300 hover:text-gold-200 transition-colors whitespace-nowrap"
                >
                  Owner sign-in
                </button>
              )}
            </div>
            {owner && (
              <p className="text-[10px] text-paper/50 mt-1 font-light">
                Signed in as {owner.name}
                {owner.associationName ? ` · ${owner.associationName}` : ''}
              </p>
            )}
          </div>

          {/* Owner sign-in view */}
          {authView === 'signin' && !owner && (
            <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5">
              <p className="text-sm text-slate-600 font-light leading-relaxed">
                Sign in once and Arthur will recognize you on this device — your
                unit, your association, your questions answered personally.
              </p>

              <button
                onClick={() => signInWithGoogle()}
                className="w-full flex items-center justify-center gap-3 bg-ink text-paper py-3.5 text-[11px] font-semibold uppercase tracking-luxe hover:bg-navy-700 transition-colors"
              >
                <svg viewBox="0 0 24 24" className="w-4 h-4" aria-hidden>
                  <path fill="#EA4335" d="M12 5.04c1.62 0 3.06.56 4.2 1.64l3.12-3.12C17.4 1.79 14.9.75 12 .75 7.55.75 3.73 3.3 1.86 7.02l3.66 2.84C6.43 7.1 8.99 5.04 12 5.04z"/>
                  <path fill="#4285F4" d="M23.25 12.27c0-.93-.08-1.6-.26-2.31H12v4.51h6.44c-.13 1.08-.83 2.7-2.39 3.79l3.57 2.77c2.14-1.97 3.63-4.88 3.63-8.76z"/>
                  <path fill="#FBBC05" d="M5.53 14.14a7.1 7.1 0 0 1-.38-2.14c0-.75.14-1.47.36-2.14L1.86 7.02A11.2 11.2 0 0 0 .75 12c0 1.8.43 3.5 1.11 4.98l3.67-2.84z"/>
                  <path fill="#34A853" d="M12 23.25c3.04 0 5.6-1 7.46-2.72l-3.57-2.77c-.95.66-2.23 1.13-3.89 1.13-3.01 0-5.57-2.06-6.48-4.75l-3.66 2.84c1.86 3.72 5.69 6.27 10.14 6.27z"/>
                </svg>
                Continue with Google
              </button>

              <div className="flex items-center gap-4">
                <span className="flex-1 h-px bg-slate-200" />
                <span className="text-[9px] uppercase tracking-luxe text-slate-400">or</span>
                <span className="flex-1 h-px bg-slate-200" />
              </div>

              {linkSent ? (
                <div className="border border-gold-300 bg-gold-50 p-4 text-sm text-slate-700 font-light leading-relaxed">
                  Check your inbox — we sent a one-click sign-in link to{' '}
                  <strong className="font-semibold">{signinEmail}</strong>. Open it on this
                  device and you&rsquo;ll be signed in automatically.
                </div>
              ) : (
                <>
                  <input
                    type="email"
                    value={signinEmail}
                    onChange={(e) => setSigninEmail(e.target.value)}
                    placeholder="Email on file with your association"
                    className="w-full border border-slate-200 px-4 py-3 text-sm font-light focus:outline-none focus:border-gold-500"
                  />
                  <button
                    onClick={async () => {
                      if (!signinEmail.includes('@')) return;
                      const ok = await sendMagicLink(signinEmail.trim());
                      if (ok) setLinkSent(true);
                    }}
                    disabled={!signinEmail.includes('@')}
                    className="w-full border border-slate-300 text-ink py-3.5 text-[11px] font-semibold uppercase tracking-luxe hover:border-gold-500 hover:text-gold-600 transition-colors disabled:opacity-40"
                  >
                    Email Me a Sign-In Link
                  </button>
                </>
              )}

              <p className="text-[10px] text-slate-400 font-light leading-relaxed">
                One sign-in per device — no passwords, no codes to retype. Use the
                email your association has on file.
              </p>
              <button
                onClick={() => setAuthView('chat')}
                className="text-[10px] uppercase tracking-luxe text-slate-500 hover:text-gold-600 transition-colors"
              >
                ← Back to chat
              </button>
            </div>
          )}

          {/* Messages */}
          {(authView === 'chat' || !!owner) && (
          <div ref={scrollRef} className="flex-1 overflow-y-auto px-5 py-5 space-y-4">
            {messages.map((m, i) => (
              <div key={i} className={m.role === 'user' ? 'flex justify-end' : 'flex justify-start'}>
                <div
                  className={
                    m.role === 'user'
                      ? 'max-w-[85%] bg-ink text-paper px-4 py-3 text-sm font-light leading-relaxed'
                      : 'max-w-[85%] bg-white border border-slate-200 px-4 py-3 text-sm text-slate-700 font-light leading-relaxed whitespace-pre-line'
                  }
                >
                  {m.role === 'assistant' ? linkify(m.content) : m.content}
                </div>
              </div>
            ))}
            {busy && messages[messages.length - 1]?.role !== 'assistant' && (
              <div className="flex justify-start">
                <div className="bg-white border border-slate-200 px-4 py-3 text-sm text-slate-400 font-light">Arthur is typing…</div>
              </div>
            )}

            {/* Arthur suggested a proposal — make acting on it one tap. */}
            {!busy && !leadMode && !leadSent &&
              messages[messages.length - 1]?.role === 'assistant' &&
              messages.length > 1 &&
              /proposal|\/contact/i.test(messages[messages.length - 1].content) && (
              <div className="flex justify-start">
                <button
                  onClick={() => {
                    setLeadMode(true);
                    setMessages((m) => [...m, { role: 'user', content: 'Request a proposal' }]);
                  }}
                  className="text-[11px] font-semibold uppercase tracking-luxe border border-gold-500 text-gold-600 px-4 py-2.5 hover:bg-gold-600 hover:text-paper transition-colors"
                >
                  Request a Proposal →
                </button>
              </div>
            )}

            {/* Lead capture */}
            {leadMode && (
              <div className="bg-white border border-gold-300 p-5 space-y-3">
                <p className="text-[10px] uppercase tracking-luxe text-gold-600">Request a Proposal</p>
                <input
                  value={lead.name}
                  onChange={(e) => setLead({ ...lead, name: e.target.value })}
                  placeholder="Your name *"
                  className="w-full border border-slate-200 px-3 py-2.5 text-sm font-light focus:outline-none focus:border-gold-500"
                />
                <input
                  value={lead.email}
                  onChange={(e) => setLead({ ...lead, email: e.target.value })}
                  placeholder="Email *"
                  type="email"
                  className="w-full border border-slate-200 px-3 py-2.5 text-sm font-light focus:outline-none focus:border-gold-500"
                />
                <input
                  value={lead.building}
                  onChange={(e) => setLead({ ...lead, building: e.target.value })}
                  placeholder="Building / association (optional)"
                  className="w-full border border-slate-200 px-3 py-2.5 text-sm font-light focus:outline-none focus:border-gold-500"
                />
                <button
                  onClick={submitLead}
                  disabled={busy || !lead.name || !lead.email}
                  className="w-full bg-ink text-paper py-3 text-[11px] font-semibold uppercase tracking-luxe hover:bg-navy-700 transition-colors disabled:opacity-40"
                >
                  Send to Our Managing Partners
                </button>
              </div>
            )}
          </div>
          )}

          {/* Quick chips */}
          {(authView === 'chat' || !!owner) && messages.length <= 2 && !leadMode && (
            <div className="px-5 pb-3 flex flex-wrap gap-2">
              {CHIPS.map((c) => (
                <button
                  key={c}
                  onClick={() => (c === 'Request a proposal' ? (setLeadMode(true), setMessages((m) => [...m, { role: 'user', content: c }])) : ask(c))}
                  className="text-xs font-light border border-slate-300 text-ink px-3.5 py-2 hover:border-gold-500 hover:text-gold-600 transition-colors"
                >
                  {c}
                </button>
              ))}
            </div>
          )}

          {/* Input */}
          {(authView === 'chat' || !!owner) && (
          <div className="border-t border-slate-200 p-4 flex gap-3">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && ask(input)}
              placeholder="Ask about payments, service, your building…"
              className="flex-1 bg-white border border-slate-200 px-4 py-3 text-sm font-light focus:outline-none focus:border-gold-500"
            />
            <button
              onClick={() => ask(input)}
              disabled={busy || !input.trim()}
              aria-label="Send message"
              className="bg-ink text-paper px-4 hover:bg-gold-600 transition-colors disabled:opacity-40"
            >
              <Send className="w-4 h-4" strokeWidth={1.5} />
            </button>
          </div>
          )}

          {(authView === 'chat' || !!owner) && (
          <div className="px-5 pb-3 flex items-center justify-between">
            <span className="text-[9px] text-slate-400 font-light">Building emergency? Call 773.728.0652</span>
            <a href="tel:7737280652" className="text-[9px] uppercase tracking-luxe text-gold-600 inline-flex items-center gap-1">
              Call now <ArrowUpRight className="w-3 h-3" />
            </a>
          </div>
          )}
        </div>
      )}
    </>
  );
}
